---
- name: Copy the WING repository definition
  copy: src=EL6.wing.repo dest=/etc/yum.repos.d/

- name: Install epel repository
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: Install nginx repository
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present
